### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by rminformaticos** [AndresGarciaSobrado91/MSI-Modern15-Hackintosh#7]
Hola que tal, tengo un portátil parecido, de igual características pero con i7, misma BIOS y el resto todo igual.

Hace tiempo que monté un hackintosh pero lo tengo un poco obsoleto jajajaja, actualmente uso OSX virtualizado con vmware, y me gustaría montarlo con Win10.

Cómo injecto la EFI y como descargo la opencore0.6.5 ya te digo q tengo oxidado el tema.

Por si me pudieras echar un cable.

Gracias

**Comment by AndresGarciaSobrado91** [comment]
Buenas como va? te agradecería una estrellita en el repo si llega a servirte.
Todo lo referido a la instalación de opencore y la inyección de EFI lo encuentras en esta guía:
https://dortania.github.io/OpenCore-Install-Guide/

Recuerda que en el código falta todo lo referido a platform-id (tienes que generarlos tu mismo e incrustarlos)
Saludos!

**Comment by rminformaticos** [comment]
Hola Andres, gracias por tu pronta ayuda. Lo de la estrella, creo que ya estaría.

He estado viendo el videotutorial: https://www.youtube.com/watch?v=U8vV2Lpb580

Tengo el usb creado, como dice en el video, me faltaría lo del platform-id que no veo como generarlo. Voy a seguir buscandolo en el enlace que me diste.

He deshabilitado lo de la bios y tal todo ok, he probado a bootear el usb y no me da para conectar al wifi.

Sigo probando y te voy diciendo.

**Comment by AndresGarciaSobrado91** [comment]
Recorda que para usar el wifi tenes que instalar HeliPort: https://github.com/OpenIntelWireless/HeliPort/releases

**Comment by AndresGarciaSobrado91** [comment]
otra recomendacion es que bajes directamente la iso del instalador full de bigSur que no requiere internet

**Comment by rminformaticos** [comment]
> otra recomendacion es que bajes directamente la iso del instalador full de bigSur que no requiere internet

Es lo q he pensado. En vez de poner el dmg del recovery pongo el otro no??? Buscaré a ver dónde descargarlo pq sólo he visto la beta. Alguna idea???

Lo del Heliport lo he visto q hay q instalarlo posteriormente.

Ya te iré contando. Gracias

**Comment by AndresGarciaSobrado91** [comment]
tenes un mac a mano? https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os

**Comment by rminformaticos** [comment]
> tenes un mac a mano? https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os

Si, tengo un vmware con os Catalina q es el q uso ahora.

Mañana miro el link y lo descargo de ahí.

Gracias ya t contaré la experiencia jeje

**Comment by rminformaticos** [comment]
Hola otra vez, ya descargué Big Sur 11.2.3 y creé el USB desde un OSX Catalina virtualizado en VmWare el USB de la instalación, habilito el EFI del usb con el mountEfi y le pego la carpeta tuya con los valores mios en el config.plist

Meto el USB, inicio la instalación y cuando faltan 12 minutos se reinicia sólo. Voy a iniciar otra vez desde el USB, en el menu hay uno q pone Big Sur Installation, le doy y se vuelve a reiniciar, y luego ya el USB queda "inservible", o sea que no sale el menu del opencore para elegir, va directamente a la instalación fallida y vuelve a reiniciarse.

Lo estoy intentando instalar en una partición en un segundo SSD M2 que le metí al portátil. Vamos ahora tengo el que viene original de 512GB y otro de 1TB, en este tengo 2 particiones de 500GB +- y quiero instalarlo en una ya formateada como HFS+ durante el proceso de instalación del OSX.

Ideas???

Gracias

**Comment by AndresGarciaSobrado91** [comment]
Por qué quedaría inservible el USB? Algo esta modificando el EFI y no debería. Me dejas las características de tu laptop?

**Comment by rminformaticos** [comment]
Es raro, la verdad lo del USB, lo estoy volviendo a generar otra vez desde el OSX virtualizado.

Te sirve con esto???

```
Model: MSI Modern 15 A10M-486XES
BIOS Version:                 E1551IMS.10E
BIOS Release Date:            2020/10/14
CPU:                          Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Memory:                       16 GB @ 1333 MHz
                               - 16 GB, DDR4-2667, Samsung M471A2G43AB2-CWE    
Graphics:                     Intel(R) UHD Graphics, 1024 MB
VBIOS Version:                N/A
Drive:                        SSD, Micron_2210_MTFDHBA512QFD, 476,94 GB
Drive:                        SSD, KINGSTON SA2000M81000G, 931,51 GB
Network:                      Intel(R) Wireless-AC 9560 160MHz
```

**Comment by rminformaticos** [comment]
Igual es eso que dices de la bios, dónde está esa opción??? Cuando termine de generarse el USB lo miro y hago fotos de la opción que me digas de la bios.

Lo único que modifiqué en BIOS fue lo que pone hla63 en su github:

```
Make sure you have disabled secure boot in bios.
You had to disabled CFG Lock in bios.
At startup press suppr key to enter in bios.
Go to Advanced menu & press the magic combo keys
Press ALT + RIGHT-CTRL + RIGHT-SHIFT together then press F2 for see hidden feature
Note (press also fn keys for azerty users)
go to advanced->power & Performance ->CPU - Power Management Control ->CPU lock Configuration ->CFG lock
```

**Comment by AndresGarciaSobrado91** [comment]
Me refiero a seleccionar la opcion de booteo primaria como tu pendrive donde tienes cargado tu EFI, asi, de forma automática, siempre booteara tu pendrive, inclusive en medio de la instalacion de macOS

**Comment by rminformaticos** [comment]
![IMG_20210318_082130](https://user-images.githubusercontent.com/3592897/111589013-99497500-87c4-11eb-9cae-8447a4d56d9b.jpg)
![IMG_20210318_082149](https://user-images.githubusercontent.com/3592897/111589025-9e0e2900-87c4-11eb-8c28-2a040eda8855.jpg)
![IMG_20210318_082229](https://user-images.githubusercontent.com/3592897/111589038-a0708300-87c4-11eb-9322-55a777b757f7.jpg)

Ésta es la configuración de BIOS que tengo. El boot sequence que dices si que tengo primero el USB pero inicia Windows.

Luego recojo un adaptador USB rj45 de tplink q es compatible con Mac para probar también la instalación desde el recovery con internet.

Gracias por tu ayuda

**Comment by AndresGarciaSobrado91** [comment]
Ahi esta tu error. Tienes que dejarlo configurado así :
![16160681931932189962488248300664](https://user-images.githubusercontent.com/48637183/111621635-fa724800-87c6-11eb-8081-bf7f45166324.jpg)

**Comment by rminformaticos** [comment]
He probado con esa configuración y al llegar al minuto 12 se reinicia continuamente, entra en bucle.
Sale esto:
![IMG_20210318_134449](https://user-images.githubusercontent.com/3592897/111628433-7fbe2280-87f0-11eb-98e6-62e41914a8cd.jpg)

Si pulso ESC me sale el menú de opencore y puedo seleccionar Windows, instalar otra vez osx y la que se reinicia continuamente es Mac OSX Installer.

**Comment by AndresGarciaSobrado91** [comment]
Ok, deberías entonces usar openCore en modo debug, obtener los logs y luego revisar https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start para determinar que esta causando tu error

**Comment by rminformaticos** [comment]
Hola, disculpa pero no me aclaro en activar el modo debug, como dices.

Modifico el config.plist cambiando estos valores:

![debug](https://user-images.githubusercontent.com/3592897/111647394-bbfa7e80-8802-11eb-9076-d7f13da89bb1.JPG)

Pero al reiniciar, hace lo mismo, se reinicia continuamente con el mismo mensaje.

**Comment by AndresGarciaSobrado91** [comment]
no, en la guia de openCore te explica que tienes que cambiar varios archivos de openCore. Asegurate que estes usando la misma version de openCore.
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#file-swaps

**Comment by AndresGarciaSobrado91** [comment]
Creo que es necesario que leas toda la guia para entender bien todo el proceso

**Comment by rminformaticos** [comment]
Si ahora lo acabo de ver jejeje. Usas la 0.65 no???

Yo en el usb en la particion EFI borro todo lo que hay, y únicamente pongo la carpeta EFI de tu github (con mis seriales).

Ya he visto donde descargar la 0.65 debug, cambio los archivos y pongo capturas

**Comment by rminformaticos** [comment]
Archivos cambiados por los de modo DEBUG en versión 0.65 con el target=67 en el config.plist

Me genera este .txt

[opencore-2021-03-18-162243.txt](https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh/files/6165295/opencore-2021-03-18-162243.txt)

**Comment by rminformaticos** [comment]
Archivos cambiados por los de modo DEBUG en versión 0.65 con el target=67 en el config.plist

Me genera este .txt

[opencore-2021-03-18-162243.txt](https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh/files/6165313/opencore-2021-03-18-162243.txt)

**Comment by AndresGarciaSobrado91** [comment]
No estoy encontrando algun error específico. Luego del reinicio estás seleccionando esta esta opcion? porque es normal el reinicio durante la instalación hasta 3 veces.
![image](https://user-images.githubusercontent.com/48637183/111778730-e7797980-8893-11eb-96a9-de79d3a84b37.png)

**Comment by rminformaticos** [comment]
Si si esa opción es la q escojo. Estoy usando el BigSur 11.3 no sé si influirá? Y el EFI es borrar lo que hay y copiar todo el q tienes en tu GitHub no??? Obviamente con mis seriales.

Es que se me hace muy muy raro.

**Comment by AndresGarciaSobrado91** [comment]
mm no lo se, 11.3 es beta, la ultima oficial es 11.2.3. Si deberia ser copiar y pegar agregando tus seriales

**Comment by AndresGarciaSobrado91** [comment]
ok acabo de descubrir que uno de tus ssd (MICRON) no es compatible con macOS, podrias desconectarlo y probar instalarlo nuevamente?

**Comment by rminformaticos** [comment]
Ok, he intentado probar quitándo el ssd solamente, pero al tener otra particion ntfs con datos me sale error al instalar BigSur.

Mañana dejaré montado sólo el SSD KINGSTON SA2000M81000G, 931,51 GB que ese me dices que es compatible, con 1 partición hfs+ únicamente para instalar el bigsur y probaré así.

Es raro que el SSD Micron no sea compatible, ya que es el que venía montado de serie en el laptop MSI, a ti te venía montado otro modelo??? Será que en el modelo con i7 montan ese ssd de esa marca.

Te digo novedades. Muchas gracias por tu ayuda amigo.

**Comment by AndresGarciaSobrado91** [comment]
Si, mi laptop trajo un Western Digital wdc pc sn530

**Comment by rminformaticos** [comment]
Bueno por fin, te escribo desde OSX Big Sur 11.2.3 
El problema era que el USB que estaba generando desde VMware no estaba bien y se copiaba mal o no hacía bien la instalación. Lo hice desde Windows con lo del modo recovery con un usb/rj45 tplink para que me diera red y a la primera instalado en el SSD Kingston de 1TB, luego ya monté el segundo SSD con Windows, y Opencore arranca perfectamente sin el USB tanto BigSur como Windows 10.

Dos consultas ya de configuración:
- Instalé Heliport y me conecta bien al Wifi, pero lo tengo que iniciar cada vez que arranco el laptop, cómo lo puedo poner para que se autoarranque???
- Uso una segunda pantalla, un monitor LG de 21" que me detecta perfectamente, pero cada vez que arranco tengo que desconectar y conectar el HDMI para que BigSur detecte la segunda pantalla, hay alguna manera de que la coja automáticamente sin necesidad de quitar/poner el cable???

Me falta poner el ID de Apple, que no me acordaba de la contraseña y tuve que hacer el recuerdo y dice que va a tardar en hacer la comprobación de no sé qué 24h, pero bueno esto será sencillo.

Muchísimas gracias por tu ayuda amigo.

**Comment by AndresGarciaSobrado91** [comment]
Qué buena noticia! Sí, eh corroborado lo del audio y también me está pasando. No lo había notado porque uso auriculares bluetooth. Habría que probar si con otro layout id diferente para el appleALC se soluciona. Con respecto al HDMI no lo he probado. Cuando pueda te cuento. Saludos!

**Comment by AndresGarciaSobrado91** [comment]
Resuelto el tema de los auriculares, debes usar alcid = 28 en tu config.plist. Voy a estar actualizando el repo en estos dias con kexts actualizados y opencore 0.6.7. Para lo del HDMI no tengo una solución por el momento. Saludos.

**Comment by rminformaticos** [comment]
Ok, lo de los kexts actualizados y opencore 0,67 perfecto, me parece una gran idea.

Lo de los auriculares, no veo la rama donde cambiar el alcid

Gracias y saludos

**Comment by afkcodes** [comment]
@AndresGarciaSobrado91 is there anyway to reach you out for fixing hdmi ? i don't have the same laptop would you be able to help ?

**Comment by AndresGarciaSobrado91** [comment]
kexts y OC actualizados con muchas mejoras. Gracias!

**Comment by AndresGarciaSobrado91** [comment]
> @AndresGarciaSobrado91 is there anyway to reach you out for fixing hdmi ? i don't have the same laptop would you be able to help ?

Do you have a Reddit account?

**Comment by rminformaticos** [comment]
> kexts y OC actualizados con muchas mejoras. Gracias!

Que tal amigo??? El portátil ha ido perfecto todo este tiempo, el otro día se actualizó a 11.6 y bien también.

Probaré los nuevos kexts y oc. Sobreescribo todo con lo nuevo, modificando el smbios y el config.plist con mis datos, alguna consideración más??

Gracias por tu ayuda y esfuerzo

**Comment by rminformaticos** [comment]
Listo, acabo de actualizar los archivos, y funciona perfecto, si las actualizaciones automáticas las tengo deshabilitadas. Acabo de probar el lector de SD y funciona perfectamente.

Hace falta actualizar el HeliPort??? o es el mismo que antes.

Gracias y saludos!

**Comment by AndresGarciaSobrado91** [comment]
Perfecto, solo por las dudas desinstala la version actual de Heliport e instala la version incluida en el repo 👌

**Comment by rminformaticos** [comment]
Hola Andrés que tal??? Me salió la actualización a Monterey, la has aplicado??? Funciona bien???

Gracias y saludos!!!

**Comment by AndresGarciaSobrado91** [comment]
Como estas? Aun no he actualizado. Avisaré por aquí en cuanto lo haga 👌

**Comment by rminformaticos** [comment]
Hola Andrés qué tal??? Feliz 2022, alguna novedad con la actualización a Monterrey???

Gracias amigo

**Comment by AndresGarciaSobrado91** [comment]
Como estas? Disuculpas por la demora, no pude trabajar con este asunto debido a mucho mucho trabajo y cuestiones personales. He actualizado el EFI para soportar macOS Monterrey. Debería funcionar todo, aunque quizás tengas algún que otro problema con el bluetooth luego de salir del modo sleep. Saludos!
